---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
  - name: concourse-example
    type: git
    source:
      uri: https://github.com/dduleone/concourse-example.git
      branch: master

  - name: pull-request
    type: pull-request
    check_every: 1m
    source:
      repository: dduleone/concourse-example
      repo: dduleone/concourse-example
      access_token: ((github-access-token))

jobs:
  - name: run-script
    public: true
    serial: true
    plan:
      - get: pull-request
        trigger: true
        version: every
      - get: concourse-example
      - get: pull-request
        params:
          list_changed_files: true
      - put: pull-request
        params:
          label: "tagged"
      - task: run-task
        file: concourse-example/task.yml
