---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
  - name: concourse-example
    type: git
    source:
      uri: https://github.com/dduleone/concourse-example.git
      branch: master

  - name: concourse-example
    type: pull-request
    check_every: 1m
    source:
      uri: https://github.com/dduleone/concourse-example.git
      branch: master

jobs:
  - name: run-script
    public: true
    serial: true
    plan:
      - get: concourse-example
        trigger: true
      - task: run-task
        file: concourse-example/task.yml
